### ISSUE TITLE
[PE-D] Restricting of adding students to lesson

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-3/tp#202]
![image.png](https://raw.githubusercontent.com/cedricongjh/ped/main/files/eb0c3cec-62eb-4433-b099-ebadfc40a36f.png)

In the UG, it states that we cannot add users if they are already in the same lesson, however, it seems that it should be allowed, or also it should indicate which students are causing the issue such that we can know which one remove from the indexes, especially when there is a long list of students

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: cedricongjh/ped#14

**Comment by JunWei3112** [comment]
To be further clarified
