### ISSUE TITLE
[PE-D] Adding new lesson for student after marking as paid does not change payment status

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-3/tp#215]
![image.png](https://raw.githubusercontent.com/cedricongjh/ped/main/files/f0b1959d-7f2c-4ac2-95f9-4b5fd45d88c0.png)

A current student with 2 lessons, Alex Yeoh, who has already paid for 2 lessons, when adding a new lesson, the payment status is still the same, when it might be different (student can sign up for a new class and hasn't paid for that month)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: cedricongjh/ped#9

**Comment by wpinrui** [comment]
To resolve by removing payment feature
